#!/bin/bash
set -e

if getent passwd ${INSTALL_USER} > /dev/null 2>&1; then
    echo "User exists"
else
    useradd --uid 1000 ${INSTALL_USER}
fi

if [ "$#" -eq 0 -o "${1:0:1}" = '-' ]; then
	set -- pg_upgrade "$@"
fi

if [ "$1" = 'pg_upgrade' -a "$(id -u)" = '0' ]; then
	mkdir -p "$PGDATAOLD" "$PGDATANEW"
	chmod 700 "$PGDATAOLD" "$PGDATANEW"
	chown ${INSTALL_USER} .
	chown -R ${INSTALL_USER} "$PGDATAOLD" "$PGDATANEW"
	exec gosu ${INSTALL_USER} "$BASH_SOURCE" "$@"
fi

if [ "$1" = 'pg_upgrade' ]; then
	if [ ! -s "$PGDATANEW/PG_VERSION" ]; then
		PGDATA="$PGDATANEW" eval "initdb $POSTGRES_INITDB_ARGS"
	fi
fi

exec "$@"
